# Site settings
title: Carissa Melanson
email: carissa.leos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Carissa tries to explain it all. Daily thoughts and projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carissamelanson.com" # the base hostname & protocol for your site
twitter_username: carissamelanson
github_username:  carissamelanson

# Build settings
markdown: kramdown
style: compressed
paginate: 6
paginate_path: "/blog/page:num/"